name: Build, SonarQube Scan, and Email

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - prod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload SonarQube Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: .scannerwork/report-task.txt

  generate_pr:
    name: Generate PR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate PR
        run: |
          # Add your PR generation steps here
          echo "Generating PR..."

  email:
    name: Send Email
    runs-on: ubuntu-latest
    needs: [build, generate_pr]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SonarQube Report Artifact
        uses: actions/download-artifact@v2
        with:
          name: sonarqube-report

      - name: Fetch SonarQube Issues
        run: |
          curl -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ secrets.SONAR_HOST_URL }}/api/issues/search?componentKeys=new-repo-php-testing&resolved=false" \
            -o sonarqube-issues.json

      - name: Send SonarQube Report via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: SonarQube Report
          body: email-body.txt
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          attachments: sonarqube-issues.json
          content_type: application/json
main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    needs: [email]
    if: ${{ needs.email.result == 'success' && github.event_name == 'pull_request' && github.event.action == 'opened' }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Add Reviewer
        id: add_reviewer
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -d '{
                  "reviewers": ["triniha"]
                }')
          echo "::set-output name=response::${response}"

      - name: Wait for PR Approval
        id: wait_for_approval
        run: echo "Waiting for PR approval"
